### ISSUE TITLE
Missing error handling

### ISSUE THREAD

**Issue by sniarn** [karimkaylani/alfred-sonoscontroller#2]
Hey

Thanks for the workflow. Was thinking about doing one myself based on SoCo, and then I saw you had beat me to it.

Anyway, if you enter a non existing speaker name, the workflow will throw an error in your face.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/4957636/81410995-f35bc180-9141-11ea-876f-b93bc32df6e9.png">

**Comment by karimkaylani** [comment]
Hi!

This is fixed in the [latest release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/tag/1.3) which also adds search filtering :)

The update should be applied automatically, but if you'd like to update manually you can type <code>soco workflow:update</code> into Alfred

Thanks so much for the feedback!

**Comment by sniarn** [comment]
👏
