### ISSUE TITLE
No speakers found

### ISSUE THREAD

**Issue by wrjlewis** [karimkaylani/alfred-sonoscontroller#3]
`func(self)
  File "sonos.py", line 28, in main
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable`

Looks like it can't find my speakers. Possible an issue with the soco library rather than this workflow?

**Comment by karimkaylani** [comment]
That's odd, it looks like the soco.discover() method is returning a NoneType rather than a set object so your suspicion is right. Maybe ensure you're connected to the same network as your speakers?

**Comment by wrjlewis** [comment]
Yep definitely on the same wifi. I have another Sonos app that is able to connect and discover correctly.

Looks like an issue within soco's discover method, I've read reports that it's unable to choose the right interface which could be the issue.

**Comment by karimkaylani** [comment]
I did some research and found that this error is common among people using VPNs since they aren't supported by Sonos, so if you are using one I'd recommended disabling it and see if that works.

If the problem still persits, I've added an interface_address environment variable in the [latest release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/tag/1.3.1) so you can set it to your local IP address manually. Check out the new [troubleshooting section](https://github.com/karimkaylani/alfred-sonoscontroller#troubleshooting) on the README for more info :)

**Comment by wrjlewis** [comment]
Thanks for the quick update! Can confirm that the VPN was indeed the issue.
