### ISSUE TITLE
Commands triggered without actioning items

### ISSUE THREAD

**Issue by sniarn** [karimkaylani/alfred-sonoscontroller#5]
If you enter a command like `soco <speaker>;play` the speaker in question will just start playing without actioning the item (without pressing ↵).

**Comment by karimkaylani** [comment]
Hi!

Unfortunately, this is unavoidable in the current state of the workflow based on the nature of how queries are executed as commands. This was mainly done so that [hotkeys](https://github.com/karimkaylani/alfred-sonoscontroller#hotkeys) can be executed quickly and easily just by adding a text argument. 

However, I've added a visual indicator in the [latest release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/tag/1.3.1) for when a command is typed directly into the Alfred search bar to help alleviate this 

[![INSERT YOUR GRAPHIC HERE](https://i.imgur.com/28rtsdf.jpg)]()
