### ISSUE TITLE
Switch between AUX input and Queue

### ISSUE THREAD

**Issue by gargs** [karimkaylani/alfred-sonoscontroller#6]
I just found this workflow and love it! Thanks for making it 🙂

Would it be possible to control the speaker so that I am able to use the workflow to switch between the aux input and the queue? That would be great. I am new to Alfred, but is there a way to also set global keyboard shortcuts for Alfred workflows?

For example: Tell Sonos speaker in the office to lower volume.

**Comment by karimkaylani** [comment]
Thank you so much for the kind words and the suggestion!

I've gone ahead and added a switch to line-in action in the [newest release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/tag/1.4).

You can also update by typing `soco workflow:update` into your alfred search bar.

Switching from aux back to queue can be a bit more complicated. If it works on your music player of choice, you can enter the queue submenu and select the exact song from the queue you would like to play. It will then automatically switch from aux to queue and play that song. Here's an example of switching back and forth that way:

[![INSERT YOUR GRAPHIC HERE](http://g.recordit.co/68SnJmoFOa.gif)]()

Unfortunately, if that doesn't work for you you will have to manually start the queue to switch off aux.

---

As for keyboard shortcuts, yes there is the way! I've laid it out instructions in the [hotkeys section](https://github.com/karimkaylani/alfred-sonoscontroller#hotkeys) in the README.

For your example, you could accomplish this with the following text argument (replacing 'Office' with your actual speaker name):

Office; chvol -10

This will lower the volume of the office speaker by 10 every time the keyboard shortcut is pressed. You could also use the 'volpcg' command to set an exact volume, instead of changing relatively.

Please let me know if you have any questions! :)
